//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    //Test
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Tags_Dem = new HashSet<Tags_Dem>();
        }
    
        public int Id { get; set; }
        public string Name_Item { get; set; }
        public System.DateTime Date_Creation { get; set; }
        public string Url_Img_Original { get; set; }
        public string Url_Img_Done_Item { get; set; }
        public string Header_Text { get; set; }
        public string Text { get; set; }
        public string AspNetUsersId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tags_Dem> Tags_Dem { get; set; }
    }
}
